config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root to: "pages#home"
  get "edit", to: "pages#edit"
  patch "update", to: "pages#update"
  get "new", to: "pages#new"
  post "create", to: "pages#create"
  get "confirmed", to: "pages#confirmed"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/summary.rb
class Summary < ApplicationRecord
end

app/models/total_quantity.rb
class TotalQuantity < ApplicationRecord
  belongs_to :product

  def self.total_quantities
    products = Product.all
    total_quantities = []
    products.each do |product|
      total_quantity = 0
      carts = CartItem.where(product: product)
      carts.each do |cart|
        total_quantity += cart.quantity
      end
      total_quantities << { product: product, quantity: total_quantity }
    end
    total_quantities
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :order
  validates :name, :block, :street, :unit, :postal, :handphone, :email_address, :uniquecode, presence: true
  validates :handphone, numericality: { only_integer: true }
  validates :email_address, format: { with: /\A.*@.*\.\w+(\.\w+)?\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def create
    information = request.raw_post
    data_parsed = JSON.parse(information)
    data_parsed.each do |data|
      CartItem.create(order_id: 1, product_id: data[0]['id'].to_i, quantity: data[0]['quantity'].to_i) if data[0]['quantity'].to_i > 0
    end
  end

  def confirm!
  end

  private

  def order_params
    params.require(:order).permit(cart_items: [:quantity])
  end

  # def product_params
  #   params.require(:product).permit(
  #     :name, :price,
  #     image_attributes: [ :id, :url, :alt, :caption ],
  #     variants_attributes: [ :id, :name, :price, :_destroy ]
  #   )
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_current_user, only: %i[update new create confirmed]
  skip_before_action :verify_authenticity_token

  def home
  end

  def edit
    if params[:pages].nil?
      redirect_to root_path
    else
      @user = User.find_by(uniquecode: params[:pages][:uniquecode])
      if @user
        session[:user_id] = @user.id
      else
        redirect_to root_path, flash: { notice: "Invalid code!" }
      end
    end
  end

  def update
    if @user.update(user_params)
      redirect_to new_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @products = Product.all
    @existing = {}
    @existing_cart = []
    @remaining_credit = @user.credit
    if @user.order.nil?
      order = Order.new
      order.user = @user
      order.save!
    elsif @user.order.cart_items.any?
      @user.order.cart_items.each do |item|
        @existing[item.product.name] = item.quantity
      end
      @existing_cart = @user.order.cart_items
    end
  end

  def create
    CartItem.where(order: @user.order).destroy_all

    cart_item_params.each do |data|
      CartItem.create(
        order: @user.order,
        product: Product.find(data['id'].to_i),
        quantity: data['quantity'].to_i
        ) if data['quantity'].to_i > 0
    end

    Summary.where(email_address: @user.email_address).destroy_all

    CartItem.where(order: @user.order).each do |item|
      Summary.create(
        user: @user.name,
        address: "#{@user.block} #{@user.street} #{@user.unit} #{@user.postal}",
        handphone: @user.handphone,
        email_address: @user.email_address,
        product: item.product.name,
        quantity: item.quantity
      )
    end

    @user.credit = credits_params
    @user.save!
    OrderMailer.with(user: @user).order_created.deliver_later


    respond_to do |f|
      f.html
      f.json
    end
  end

  def confirmed
    @order = @user.order
  end

  private

  def find_current_user
    if session[:user_id].nil?
      redirect_to root_path
    else
      @user = User.find(session[:user_id])
    end
  end

  def cart_item_params
    params.fetch(:cart_items)
  end

  def credits_params
    params.require(:credits)
  end

  def order_params
    params.require(:order).permit(:id)
  end

  def user_params
    params.require(:user).permit(:name, :block, :street, :unit, :postal, :handphone, :email_address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    if @product.save == true
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramadhan on Wheels 2023</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="container d-flex justify-content-center align-items-center flex-column min-vh-100">
    <%= yield %>
  </body>
</html>

app/views/layouts/bootstrap-mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_basket_table.html.erb
<div class="basket-tables" data-id="list-<%= basket_item.product.id %>">
  <p class="item"><%= basket_item.product.name %></p>
  <p class="cost"><%= basket_item.product.cost %></p>
  <p class="number"><%= basket_item.quantity %></p>
</div>

app/views/orders/index.html.erb
<% @order.cart_items.each do |item| %>
<p><%= item.product.name %></p>
<p><%= item.quantity %></p>
<% end %>

app/views/pages/_code.html.erb
<%= simple_form_for :pages, url: edit_path, method: :get do |f| %>
  <%= f.input :uniquecode, label: 'uniquecode*', required: true %>
<p id="notice" class="m-0 text-danger"><%= notice %></p>
  <%= f.submit "Log In", class: "common-button" %>
<% end %>

app/views/pages/_footer.html.erb
<div class="footer textcenter my-3">
  <p>Need Help?</p>
  <p class="m-0">Contact via Whatsapp</p>
  <p class="m-0">ROW Admin 83003852</p>
</div>

app/views/pages/confirmed.html.erb
<div class="textcenter d-flex flex-column align-items-center justify-content-center col-12 col-lg-6 mt-4">
  <%= image_tag "checked.png", class: "w-25" %>
  <div class ="confirmationbar py-1 px-4 my-4">
    <h2 class="m-2">Your order is confirmed!</h2>
    <br>
    <p>You should receive a confirmation email very soon! </p>
    <p>If you do not receive any email, please contact us below.</p>
  </div>
</div>

<div class="row justify-content-center mx-1">
  <div class="order-summary content d-flex flex-column p-4 px-lg-5 rounded-4 col-12 col-lg-5 my-2 mx-1">
    <h2 class="text-center"><strong>Confirmed Order</strong></h2>
    <div class="cart-summary textcenter row">
        <p class="col-2 p-0 mx-0 my-auto"><strong>No</strong></p>
        <p class="col-2 p-0 mx-0 my-auto flex-grow-1"><strong>Item</strong></p>
        <p class="col-2 p-0 mx-0 my-auto"><strong> </strong></p>
        <p class="col-2 p-0 mx-0 my-auto"><strong>Credit</strong></p>
        <p class="col-2 p-0 mx-0 my-auto"><strong>Qty</strong></p>
    </div>
      <% @order.cart_items.each_with_index do |cart, index| %>
        <div class="cart-summary textcenter row my-1">
          <p class="col-2 p-0 mx-0 my-auto"><%= index + 1 %></p>
          <p class="col-2 p-0 mx-0 my-auto flex-grow-1"><%= cart.product.name %></p>
          <p class="col-2 p-0 mx-0 my-auto"><%= cart.product.description %></p>
          <p class="col-2 p-0 mx-0 my-auto"><%= cart.product.cost %></p>
          <p class="col-2 p-0 mx-0 my-auto"><%= cart.quantity %></p>
        </div>
      <% end %>
  </div>

  <div class="user-summary content d-flex flex-column p-4 px-lg-5 rounded-4 col-12 col-lg-5 my-2 mx-1">
    <div class="user-details">
      <h2 class="text-center"><strong>Details</strong></h2>
        <p class="m-0"><strong>Name: </strong><%= @user.name %></p>
        <p class="m-0"><strong>Phone Number: </strong><%= @user.handphone %></p>
        <p class="m-0"><strong>Email Address: </strong><%= @user.email_address %></p>
        <p class="m-0"><strong>Delivery Address: </strong><%= @user.block %> <%= @user.street %> <%= @user.unit %> <%= @user.postal %> </p>
        <br>
    </div>

    <div class="note">
      <h2 class="text-center"><strong>Note</strong></h2>
      <ol class="px-3 px-lg-2">
          <li>Any unused remaining credits will be deleted and unclaimable.</li>
          <li>Items selected are subject to availability. Alternative items of similar value may be provided instead.</li>
          <li>Delivery date will be between <strong>3 April - 6 April</strong>, between 10am - 6pm (Confirmed date and timing will be informed closer to date via text). Unfortunately, no specific timing will be given and you will not be able to choose a timing.</li>
          <li>Please ensure that someone is home to receive the items.</li>
      </ol><br>
    </div>
  </div>
</div>
<%= render "pages/footer" %>

app/views/pages/edit.html.erb
<div class="textcenter my-2">
  <h1>Please confirm your details</h1>
</div>
<div class="content editpage p-4 rounded-4 col-12 col-lg-6">
  <div></div>
  <%= simple_form_for @user, url: update_path, method: :patch, html: { class: "textcenter"} do |f| %>
    <%= f.input :name, label: 'Name', required: true %>
    <%= f.input :block, label: 'Block', required: true %>
    <%= f.input :street, label: 'Street', required: true %>
    <%= f.input :unit, label: 'Unit', required: true %>
    <%= f.input :postal, label: 'Postal', required: true %>
    <%= f.input :handphone, label: 'Handphone', required: true %>
    <%= f.input :email_address, label: 'Email Address', required: true %>
    <%= f.button :submit, class: "common-button", value: "Save & Submit" %>
    <% end %>
</div>
<%= render "pages/footer" %>

app/views/pages/home.html.erb
<div class="content d-flex flex-column py-5 px-3 px-lg-5 rounded-4 col-12 col-lg-6">
  <div class="introheader">
    <h1>Welcome to the 4PM ROW 2023!</h1>
  </div>
  <div class="textcenter mb-2">
    <p>Please input your code given by 4PM staff<br>
    Note: Only small letters</p>
  </div>
  <div class="textcenter">
    <%= render "pages/code", pages: @pages %>
  </div>
</div>
<%= render "pages/footer" %>

app/views/pages/new.html.erb
<div class="new-body"  data-controller="cartcollator">
  <div class="left-body">
    <div class="new-note">
      <h3>Note</h3>
      <ol>
        <li>Any unused remaining credits will be deleted and unclaimable.</li>
        <li>Items selected are subject to availability. Alternative items of similar value may be provided instead.</li>
        <li>You can select up to a maximum of 3 for each item.</li>
      </ol>
    </div>
    <div class="new-staples mb-2">
        <div class="accordion" id="accordion-staples" data-action="counter:increment@document->totalcredits#update counter:decrement@document->totalcredits#update">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Staples
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <div class="staples-header">
                  <p class="header item">Items</p>
                  <p class="header credit">Credit</p>
                  <p class="header selection">Selection</p>
                </div>
                  <% @products.each do |product| %>
                  <% if product.category == "Staples" %>
                    <div class="staples-header" data-controller="counter" data-counter-target="basket" data-counter-existing-value="<%= @existing_cart.to_json %>">
                      <div class="item">
                        <div class="item-photo">
                          <%= image_tag product.path, width: 40 %>
                          <p class="text-center p-0 fw-bold text-muted"><%= product.description%></p>
                        </div>
                        <div class="item-text">
                          <p data-counter-target="name"><%= product.name%></p>
                        </div>
                      </div>
                      <div class="credit">
                        <p data-counter-target="cost"><%= product.cost%></p>
                      </div>
                      <div class="selection">
                        <div class="decrement mx-2" data-action="click->counter#decrement"><i class="fa-solid fa-caret-left fa-2xl"></i></div>
                        <div class="value" data-counter-target="value" data-id="<%=product.id%>"><%= @existing[product.name] || 0 %></div>
                        <div class="increment mx-2" data-action="click->counter#increment"><i class="fa-solid fa-caret-right fa-2xl"></i></div>
                      </div>
                    </div>
                    <% end %>
                  <% end %>
                </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Hari Raya Goodies
              </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <div class="staples-header">
                  <p class="header item">Items</p>
                  <p class="header credit">Credit</p>
                  <p class="header selection">Selection</p>
                </div>
                    <% @products.each do |product| %>
                  <% if product.category == "Hari Raya Preparation" %>
                    <div class="staples-header" data-id="<%=product.id%>" data-controller="counter">
                      <div class="item">
                        <div class="item-photo">
                          <%= image_tag product.path, width: 40 %>
                          <p class="text-center p-0 fw-bold text-muted"><%= product.description%></p>
                        </div>
                        <div class="item-text">
                          <p data-counter-target="name"><%= product.name%></p>
                        </div>
                      </div>
                      <div class="credit">
                        <p data-counter-target="cost"><%= product.cost%></p>
                      </div>
                      <div class="selection">
                        <div class="decrement mx-2" data-action="click->counter#decrement"><i class="fa-solid fa-caret-left fa-2xl"></i></div>
                        <div class="value" data-counter-target="value" data-id="<%=product.id%>"><%= @existing[product.name] || 0 %></div>
                        <div class="increment mx-2" data-action="click->counter#increment"><i class="fa-solid fa-caret-right fa-2xl"></i></div>
                      </div>
                    </div>
                    <% end %>
                  <% end %>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Cleaning Essentials
              </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <div class="staples-header">
                  <p class="header item">Items</p>
                  <p class="header credit">Credit</p>
                  <p class="header selection">Selection</p>
                </div>
                <% @products.each do |product| %>
                  <% if product.category == "Cleaning Essentials" %>
                    <div class="staples-header" data-id="<%=product.id%>" data-controller="counter">
                      <div class="item">
                        <div class="item-photo">
                          <%= image_tag product.path, width: 40 %>
                          <p class="text-center p-0 fw-bold text-muted"><%= product.description%></p>
                        </div>
                        <div class="item-text">
                          <p data-counter-target="name"><%= product.name%></p>
                        </div>
                      </div>
                    <div class="credit">
                        <p data-counter-target="cost">
                    <%= product.cost%></p></div>
                      <div class="selection">
                        <div class="decrement mx-2" data-action="click->counter#decrement"><i class="fa-solid fa-caret-left fa-2xl"></i></div>
                        <div class="value" data-counter-target="value" data-id="<%=product.id%>"><%= @existing[product.name] || 0 %></div>
                        <div class="increment mx-2" data-action="click->counter#increment"><i class="fa-solid fa-caret-right fa-2xl"></i></div>
                      </div>
                    </div>
                    <% end %>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="right-body" data-controller="totalcredits" data-action="counter:increment@document->totalcredits#update counter:decrement@document->totalcredits#update" data-controller="counter">
    <div class="new-baskets">
      <h3>Your basket</h3>
      <div class="basket-tables" >
        <p class="table-header item">Items</p>
        <p class="table-header cost">Credit</p>
        <p class="table-header number">Selection</p>
      </div>
      <div class="basket-tables-insert">
        <% @existing_cart.each_with_index do |basket_item, index| %>
          <%= render 'orders/basket_table', basket_item: basket_item, index: index %>
        <% end %>
      </div>
      <h3 class="text-orange">Remaining Credits: <span data-totalcredits-target="total" data-cartcollator-target="total" id="remaining-credit"> <%= @remaining_credit %></span></h3>
      <div class="basket-note">
        <p>Any unused remaining credits will be deleted and unclaimable</p>
      </div>
    </div>
    <div class="new-reminder">
      <h3>Reminder</h3>
        <ol>
          <li>Items selected are subject to availability. Alternative items of similar value may be provided instead.</li>
          <li>Delivery date will be between <strong>3 April - 6 April</strong>, between 10am - 6pm (Confirmed date and timing will be informed closer to date via text). Unfortunately, no specific timing will be given and you will not be able to choose a timing.</li>
          <li>Please ensure that someone is home to receive the items.</li>
        </ol>
      <h4>No edits can be made after clicking Submit</h4>
      <button class="common-button" data-action="click->cartcollator#collate">Submit</button>
    </div>
    <%= render "pages/footer" %>
  </div>
</div>

app/views/products/index.html.erb
<div data-controller="cartcollator">
  <div data-controller="totalcredits" data-action="counter:increment@document->totalcredits#update counter:decrement@document->totalcredits#update">
    <p>Kamu ada <span data-totalcredits-target="total">150</span> credits sahaja</p>
    <button data-action="click->cartcollator#collate">Submit</button>
  <div>

  <% @products.each do |p| %>
  <div class="card-product mb-4 d-flex justify-content-between" id="card-info" data-controller="counter">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <div class="card-product-infos">
      <h2><%= p.name %></h2>
      <p><%= p.description %></p>
      <p><span data-counter-target="cost"><%= p.cost %></span> credits</p>
    </div>
    <div class="boxcounter d-flex flex-row">
      <div class="decrement mx-2" data-action="click->counter#decrement"><i class="fa-solid fa-minus"></i></div>
      <div class="value" data-counter-target="value" data-id="<%=p.id%>">0</div>
      <div class="increment mx-2" data-action="click->counter#increment"><i class="fa-solid fa-plus"></i></div>
    </div>
  </div>
  <% end %>
</div>